const wall = {
  displays: {
    1: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 0,
      offsetTopMillimeters: 0,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/3.jpg",
    },

    2: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 1209.6,
      offsetTopMillimeters: 0,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/4.jpg",
    },
    3: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 2419.2,
      offsetTopMillimeters: 0,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/9.jpg",
    },
    4: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 0,
      offsetTopMillimeters: 680.4,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/6.jpg",
    },
    5: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 1209.6,
      offsetTopMillimeters: 680.4,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/imag2.jpg",
    },
    6: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 2419.2,
      offsetTopMillimeters: 680.4,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/8.jpg",
    },
    7: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 0,
      offsetTopMillimeters: 1360.8,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/5.jpg",
    },
    8: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 1209.6,
      offsetTopMillimeters: 1360.8,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/imag-1.jpg",
    },
    9: {
      displayAreaWidthMillimeters: 1209.6,
      displayAreaHeightMillimeters: 680.4,
      bezelLeftMillimeters: 2,
      bezelRightMillimeters: 2,
      bezelTopMillimeters: 2,
      bezelBottomMillimeters: 2,
      offsetLeftMillimeters: 2419.2,
      offsetTopMillimeters: 1360.8,
      widthPixels: 1920,
      heightPixels: 1080,
      src: "https://raw.githubusercontent.com/mAdrian999/POZE/main/7.jpg",
    },
  },
};

export default wall;
